# Generated by Django 5.2.11 on 2026-03-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('admission_no', models.CharField(blank=True, max_length=100, null=True)),
                ('roll_no', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('class_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('dob', models.CharField(blank=True, max_length=50, null=True)),
                ('dob_words', models.CharField(blank=True, max_length=200, null=True)),
                ('admission_date', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('discount_amount', models.FloatField(default=0)),
                ('discount_percent', models.FloatField(default=0)),
                ('is_free', models.BooleanField(default=False)),
                ('custom_fee', models.FloatField(default=0)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('class_name', 'section_name')},
            },
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('month', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('base_fee', models.FloatField()),
                ('discount', models.FloatField(default=0)),
                ('monthly_fee', models.FloatField()),
                ('previous_due', models.FloatField(default=0)),
                ('total_payable', models.FloatField()),
                ('paid_amount', models.FloatField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='school_app.student')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('marks', models.IntegerField()),
                ('term', models.CharField(default='1st Term', max_length=100)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school_app.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='school_app.student')),
            ],
            options={
                'unique_together': {('student', 'exam', 'subject', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='school_app.student')),
            ],
            options={
                'unique_together': {('student', 'date')},
            },
        ),
    ]
