# Generated by Django 5.2.12 on 2026-04-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_app', '0004_schoolsetting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('section_name', models.CharField(blank=True, max_length=100, null=True)),
                ('day', models.CharField(max_length=20)),
                ('subject', models.CharField(max_length=100)),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(blank=True, max_length=200, null=True)),
                ('start_time', models.CharField(max_length=50)),
                ('end_time', models.CharField(max_length=50)),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='teacherclassassignment',
            name='sync_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
